server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
security:
  basic:
    enabled: true
  enable-csrf: true
  headers:
    xss: true
  ignored: /demo/*, /test/*
  user:
    name: hello
    password: world
